source("./helpers/index.R", chdir = TRUE)

install_libraries(data_description_packages)
install_libraries(exploratory_data_analysis_packages)
install_libraries(outlier_detection_packages)
install_libraries(data_reduction_packages)
install_libraries(classification_and_discrimination_packages)
install_libraries(clustering_packages)